version: '3'

networks:
  backend:
    name: backend
    driver: bridge

services:
  auth-service:
    image: registry.jahiduls.mint/auth-service:local
    container_name: auth-service
    build: $WORKSPACE/projects/backend/auth-service
    restart: unless-stopped
    environment:
      - MONGO_USER=auth
      - MONGO_PASSWORD=auth
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth
    networks:
      - backend
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.authapi.entryPoints=web
      - traefik.http.routers.authapi.rule=Host(`frontend.jahiduls.local`) && PathPrefix(`/api/auth`)
      - traefik.http.routers.authapi.service=authapi
      - traefik.http.routers.authapi.middlewares=authapi
      - traefik.http.middlewares.authapi.stripprefix.prefixes=/api/auth
      - traefik.http.services.authapi.loadbalancer.server.port=80
